[package]
name = "turnstone-client"
description = "TurnstoneDB mTLS client library"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
turnstone-protocol = { path = "../turnstone-protocol" }
turnstone-tls = { path = "../turnstone-tls" }
rustls.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.14"
