[package]
name = "turnstone-cli"
description = "TurnstoneDB CLI library and turnstone-rs client binary"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "turnstone-rs"
path = "src/main.rs"

[dependencies]
turnstone-backup = { path = "../turnstone-backup" }
turnstone-client = { path = "../turnstone-client" }
turnstone-protocol = { path = "../turnstone-protocol" }
turnstone-tls = { path = "../turnstone-tls" }
clap.workspace = true
serde_json = { workspace = true }
rand = "0.8"
rustls = { workspace = true }
