[package]
name = "turnstone"
description = "TurnstoneDB CLI (init, server, client)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "turnstone"
path = "src/main.rs"

[dependencies]
clap.workspace = true
turnstone-config = { path = "../turnstone-config" }
turnstone-client = { path = "../turnstone-client" }
turnstone-database = { path = "../turnstone-database" }
turnstone-engine = { path = "../turnstone-engine" }
turnstone-repl = { path = "../turnstone-repl" }
turnstone-server = { path = "../turnstone-server" }
turnstone-tls = { path = "../turnstone-tls" }
serde_json = { workspace = true }
